### ISSUE TITLE
Command pipes error with definition

### ISSUE THREAD

**Issue by robsonfingo** [cuelang/cue#237]
```
package foo

import (
    "encoding/json"
    "tool/exec"
    "tool/cli"
)

foo: {
  a :: string
  b: a
}

command: local_config: {
    task: getuser: exec.Run & {
        cmd: "printenv USER"
        stdout: string
    }
    task: write: cli.Print & {
        text:  json.Marshal(foo & { a :: task.getuser.stdout })
    }
}
```

```
command.local_config.task.write.text: cannot convert incomplete value "string" to JSON:
    ./local_config_tool.cue:10:8
    ./local_config_tool.cue:17:17
    tool/exec:9:20
exit status 1
```

**Comment by mpvl** [comment]
This is actually a totally different issue: the dependency analyzer doesn't walk over definitions. Fix will be there soon.

**Comment by robsonfingo** [comment]
FYI, if I write:
```text:  json.Marshal(foo & { a :: "x" })```
instead it works

**Comment by mpvl** [comment]
Yes, because then the expression is concrete. The problem in this case is (which is very different from your other bugs), that the dependency analyzer misses that there is a reference in the `write` task, causing it to run before `getuser` completes. This, in turn, is caused by the fact that it skips definitions when iterating over fields.

**Comment by robsonfingo** [comment]
Thanks a lot for the quick turnaround!

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/237.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
