### ISSUE TITLE
@tag --inject equivalent in yaml used by kpt tool is a magic comment #Ref

### ISSUE THREAD

**Issue by mikelnrd** [cuelang/cue#422]
Hi. Google's new `kpt` tooling for kubernetes does an interesting thing where it uses special `#Ref` comment in yaml files to mark where a 'setter' is. This allows other downstream importers of a kpt package to set a value.

I saw this today and immediately thought of cue's `@tag` and `--inject` functionality.

I just thought I'd flag this to the cue developers... if `kpt` tooling becomes prominent in the ecosystem (which it might as its from Google and is designed to compose with other tools), might it be useful/worth considering having cue support reading/writing magic comments like `#Ref`?!

**More context...**

```bash
kpt cfg create-setter express-web/ replicas 3
```
```yaml
replicas: 3 # {"$ref":"#/definitions/io.k8s.cli.setters.replicas"} 
```
```bash
kpt cfg set express-web replicas 2
```

This article looks like it explains kpt and the purpose of the `#Ref` comments quite well:
https://labs.meanpug.com/kubernetes-kpt-in-the-wild/

More generally it seems to me (from the outside) that kpt and cue are working in a similar area. I can see why both should exist and even work together (you can pry cue from my cold dead hands as the saying goes) - I guess I'm wondering if there's been much communication between those working on the two projects so far??

**Comment by seh** [comment]
Unlike Pulumi, _kpt_ is much closer to CUE: It wants to wrap around the transforming tools, so that you tell _kpt_ how and when to run which tools to process the JSON or YAML documents. It's a little hard to figure out whether _kpt_ considers these functions to be operating on text or on "objects". In the normal case it's passing YAML documents through them, but there are expectations about validity and preserving comments, so it's a more "structured" approach than a tool like Helm's ransom note style of cobbling together text fragments that might come together as valid YAML.

The telegraphed quotation about not building tools that call CUE comes from [the "Define commands" section](https://github.com/cuelang/cue/blob/v0.2.0/doc/tutorial/kubernetes/README.md#define-commands) of the Kubernetes tutorial. I thought I had seen more of this advice elsewhere, but can't find it in a cursory search this morning.

Here's a key paragraph:
> In practice this means typing the same commands ad nauseam. The next step is often to write wrapper tools. But as there is often no one-size-fits-all solution, this lead[s] to the proliferation of marginally useful tools. The _cue_ tool provides an alternative by allowing the declaration of frequently used commands in CUE itself. Advantages:

You mention the philosophy of "wrap[ping] code in data". It's not clear to me yet how that's either advantageous or sufficient. Tools like Bazel go in that direction, though not every problem is amenable to modeling in terms of input files, dependencies, and output files. Can you elaborate on what's bad about the antonym—presumably "wrapping data in code"?

**Comment by mpvl** [comment]
sorry, closed wrong bug.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/422.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
