### ISSUE TITLE
Avoid character '\' for interpolation

### ISSUE THREAD

**Issue by tredoe** [cuelang/cue#433]
**Is your feature request related to a problem? Please describe.**
It gives issues when you have to work with Windows paths: `('\(path.dirData)\\(dbname)\', '\(path.dirData)\\(dbname)\foo\')`

**Describe the solution you'd like**
I think that the characters `$(string)` or even `{{string}}` are better to define an interpolation, since they are not widely used into a text or path.

At bash, `$(var)` is used; the Go templates use `{{string}}`.

**Comment by mpvl** [comment]
CUE is a JSON superset, which put limitations on the choice of interpolation syntax if one wants to have just a single string syntax (which is ideal). The most obvious illegal sequence one can create in JSON is one starting with `\` followed by an unsupported escaped character. This is how we ended up with `\(`. There is precedence for this in other languages too. 

Note that, `"${foo}"` is a valid JSON string, so one would need an additional mechanism to indicate whether strings should be interpolated or not (like `@"%{foo}"`). This is not ideal.

I'm not sure what this issue is here, but note that you can use the `#"\(foo)"#` syntax to include a literal `\(` in strings. To mix both, use `#"\(foo)\#(foo)"#`, etc.

**Comment by mpvl** [comment]
Also, we don't take language changes lightly. We are moving towards stabilizing the language. I know that we recently changed the syntax of definitions, but this was to address some serious shortcomings of the previous approach. The benefit in this case fare outweighed sticking with the status quo.

**Comment by mpvl** [comment]
Closing as the requested functionality is not possible and escape delimiters should be sufficient to address the issue.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/433.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
