### ISSUE TITLE
cue: proto support

### ISSUE THREAD

**Issue by mpvl** [cuelang/cue#5]
Tracking issue for adding protobuf support to CUE:
- import command reads text and binary proto instance
- import command reads proto definitions
- export command supports the converse
- core libs

**Comment by JohnAZoidberg** [comment]
What's the status of encoding Cue values as Protobuf?
I'd like to describe my data in cue and dump is as binary using Protobuf.
Should I go through JSON and convert that to Proto3?

**Comment by mpvl** [comment]
It is not implemented so far. Should be straightforward, but stabilizing the new evaluator has priority.

But open to contributions.

**Comment by mvdan** [comment]
In case you're not aware, the new protobuf module has low-level primitive packages for encoding and decoding, for example for arbitrary data in protowire: https://pkg.go.dev/google.golang.org/protobuf@v1.26.0/encoding/protowire

https://pkg.go.dev/google.golang.org/protobuf@v1.26.0/encoding/prototext is message-based instead of token-based, though, so it's unclear if you could use it at all without a schema.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/5.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
