### ISSUE TITLE
import fails on `cue eval` within cue.mod/pkg

### ISSUE THREAD

**Issue by shykes** [cuelang/cue#551]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-alpha4 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

- Last stable release: yes
- Last alpha release: yes

### What did you do?

```
$ cat > repro.sh <<'EOF'
#!/bin/bash

set -e

# Create package to be imported
DIR_FOO=cue.mod/pkg/foo.com/foo
mkdir -p "$DIR_FOO"
echo 'package foo' > "$DIR_FOO"/foo.cue

# Create package from which to import
DIR_BAR=cue.mod/pkg/bar.com/bar
mkdir -p "$DIR_BAR"

# This works
echo -e 'import "foo.com/foo"\nfoo' | cue eval - >/dev/null && echo "Import from module root: OK"

# This doesn't work
cd $DIR_BAR && echo -e 'import "foo.com/foo"\nfoo' | cue eval - >/dev/null && echo "Import from within cue.mod/pkg/: OK"
EOF
````

```
$ bash repro.sh
```

### What did you expect to see?

```
Import from module root: OK
Import from within cue.mod/pkg/: OK
```

### What did you see instead?

```
Import from module root: OK
import failed: cannot find package "foo.com/foo":
    -:1:8
```

**Comment by verdverm** [comment]
are you trying to navigate into the `cue.mod` dir and run typical cue commands, and expecting that it ought to work as if from a normal cue module with a mod dir and packages?

iirc, the way imports work is much like Go and (again) iirc only one layer of modules is imported, so that when you run the command in from within the cue mod dir, it would need essentially the same mod dir from wherever you are trying to run the command. That is to say cue is not walking back up the directory structure to find the correct root dir of your module which has the original `cue.mod` dir.

Does this sound about right?

**Comment by shykes** [comment]
Yes that’s exactly right. I expected a “git-like” behavior of walking back up to find the current cue.mod.

I often find myself in an interactive shell typing “cue eval” within the directory of the package I’m developing or testing. This is in the context of developing a standard library so there is no “primary” package at the root of the module. The cue.mod itself is the project.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/551.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
