### ISSUE TITLE
`for` errors out on solvable cycles

### ISSUE THREAD

**Issue by Ereski** [cuelang/cue#779]
Current master (2c86835)

Similar to the previous issues I've opened, this time it's `for` that is having trouble with cycles:

```
X: Y.message

STATE: {
    for k, v in Y {
        if k != "message" {
            "\(k)": v
        }
    }
}

Y: STATE & {
    message: X
}
```

This is a simple stateful bidirectional projection expressed in CUE (`STATE` is saved and restored as needed). In one way, `Y` is forked into `X` and `STATE`. In the other way, `X` and `STATE` are joined into `Y`. Two usage examples are:

```
X: "test"

STATE: {
    code: 101
}
```

and

```
Y: {
    message: "test"
    code: 101
}
```

Both of which errors out with a cycle error. Even defining `X`, `STATE`, and `Y` all at the same time causes a cycle error.

**Comment by mpvl** [comment]
Another interesting one. :)

The cycle here is detected here because the `for` comprehension iterators over the the very struct in which it embeds.

Arguably, of course, that should be okay as long as it does not add new fields that then should have been used during evaluation. 

FTR, in v0.2 the cycle check did not work correctly and this construct would produce inaccurate results.

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/779.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
