### ISSUE TITLE
doc: chinese (and other) translations

### ISSUE THREAD

**Issue by TomorJM** [cuelang/cue#970]
Is there any plan to add Chinese version documents?

**Comment by myitcv** [comment]
Whilst we don't have an active plan for actually writing translations of any of the docs, we would very much support and welcome any such contributions. Indeed I suggest we use this issue in order to plan and coordinate any efforts, even for translations of https://cuelang.org/ (which lives at https://github.com/cuelang/cuelang.org).

**Comment by cueckoo** [comment]
This issue has been migrated to https://github.com/cue-lang/cue/issues/970.

For more details about CUE's migration to a new home, please see https://github.com/cue-lang/cue/issues/1078.
